---
#
# Installing Java 8
#

# Add the Java repo

- name: Add the Java PPA repo
  apt_repository: 
   repo: ppa:linuxuprising/java

# Accept Oracle license

- name: Automatically accept the Oracle license
  shell: echo oracle-java11-installer shared/accepted-oracle-license-v1-2 select true | sudo /usr/bin/debconf-set-selections

# Install Java

- name: Install Java 11
  apt:
   name: oracle-java11-installer
   state: present
   update_cache: yes
